refactor: Refactor JWT and OpenId recipes (JWT Rework #2)
supertokens/supertokens-golang pull request #258
Opened 2023-04-03 11:05 UTC by nkshah2

## Summary of change

- Updates the signature of `CreateJWT` and `CreateJWTWithContext` to include `useStaticSigningKey`
- Updates the url of the well known jwks endpoint exposed by the core in the getJWKS recipe function implementation

## Related issues

-   Link to issue1 here
-   Link to issue1 here

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes

(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates

-   [ ] Changelog has been updated
-   [ ] `coreDriverInterfaceSupported.json` file has been updated (if needed)
    -   Along with the associated array in `supertokens/constants.go`
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `supertokens/constants.go > version variable`
-   [ ] Had installed and ran the pre-commit hook
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR

-   [ ] Item1
-   [ ] Item2

2023-04-04 09:09 UTC, porcellus requested changes

2023-04-04 09:09 UTC, porcellus commented on recipe/jwt/jwtmodels/recipeInterface.go
> +	CreateJWT *func(payload map[string]interface{}, validitySeconds *uint64, userContext supertokens.UserContext, useStaticSigningKey *bool) (CreateJWTResponse, error)
AFAIK everywhere else, the `userContext` is the last param, I don't think we should break this pattern. Would it cause issues?

2023-04-10 09:33 UTC, rishabhpoddar requested changes

2023-04-10 09:33 UTC, rishabhpoddar commented on recipe/jwt/recipeimplementation.go
> +			"jwksDomain":          appInfo.APIDomain.GetAsStringDangerous(),
should this also have apiBasePath?

2023-04-10 09:43 UTC, merged