feat: optional password validation in updateEmailOrPassword
supertokens/supertokens-golang pull request #276
Opened 2023-05-03 08:15 UTC by iresharma

## Summary of change
Added optional password validation in `updateEmailOrPassword` function.

## Related issues

-   https://github.com/supertokens/supertokens-node/issues/549 (same implemented for golang)

## Test Plan

## Documentation changes

(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates

-   [ ] Changelog has been updated
-   [ ] `coreDriverInterfaceSupported.json` file has been updated (if needed)
    -   Along with the associated array in `supertokens/constants.go`
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `supertokens/constants.go > version variable`
-   [ ] Had installed and ran the pre-commit hook
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR

-   [ ] Item1
-   [ ] Item2

2023-05-03 09:22 UTC, iresharma commented on recipe/emailpassword/recipeImplementation.go
> +				for i := range formFields {
```suggestion
				for i := range formFields {
					if formFields[i].ID == "password" {
						err := formFields[i].Validate(*password)
						if err != nil {
							errResponse := epmodels.PasswordPolicyViolatedError{
								FailureReason: err,
							}
							return epmodels.UpdateEmailOrPasswordResponse{PasswordPolicyViolatedError: &errResponse}, nil
						}
					}
					break;
				}
```

Should I add a break statement here, there can be a lot of fields but as soon as password field is validated we can break

2023-05-03 18:33 UTC, rishabhpoddar requested changes

2023-05-03 18:33 UTC, rishabhpoddar commented on recipe/emailpassword/epmodels/recipeInterface.go
> +	FailureReason *string
```suggestion
	FailureReason string
```

2023-05-03 18:33 UTC, rishabhpoddar commented on recipe/emailpassword/epmodels/recipeInterface.go
> +	FailureReason *string
Cause if this struct is defined, there will always be a reason.

2023-05-03 18:33 UTC, rishabhpoddar commented on recipe/thirdpartyemailpassword/main.go
> +func UpdateEmailOrPasswordWithContext(userId string, email *string, password *string, applyPasswordPOlicy *bool, userContext supertokens.UserContext) (epmodels.UpdateEmailOrPasswordResponse, error) {
Capital "O" in POlicy.. Please double check your PRs.

2023-05-03 18:33 UTC, rishabhpoddar commented on recipe/thirdpartyemailpassword/main.go
> +	return (*instance.RecipeImpl.UpdateEmailOrPassword)(userId, email, password, applyPasswordPOlicy, userContext)
```suggestion
	return (*instance.RecipeImpl.UpdateEmailOrPassword)(userId, email, password, applyPasswordPolicy, userContext)
```

2023-05-04 05:52 UTC, rishabhpoddar requested changes

2023-05-04 05:52 UTC, rishabhpoddar commented on recipe/emailpassword/updateEmailPass_test.go
>  }
add more tests

2023-05-04 05:52 UTC, rishabhpoddar commented on recipe/thirdpartyemailpassword/recipe.go
> +	var emailPasswordRecipe emailpassword.Recipe
undo change for where this variable was

2023-05-04 08:34 UTC, rishabhpoddar approved these changes

2023-05-04 08:34 UTC, merged