fix: normaliseSessionScope and add tests
supertokens/supertokens-golang pull request #410
Opened 2024-05-01 08:18 UTC by anku255

## Summary of change

Fixes the `normaliseSessionScopeOrThrowError` function and adds tests for it.

## Related issues

-   Link to issue1 here
-   Link to issue1 here

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes

(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates

-   [ ] Changelog has been updated
-   [ ] `coreDriverInterfaceSupported.json` file has been updated (if needed)
    -   Along with the associated array in `supertokens/constants.go`
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `supertokens/constants.go > version variable`
-   [ ] Had installed and ran the pre-commit hook
-   [ ] If new thirdparty provider is added,
    -   [ ] update switch statement in `recipe/thirdparty/providers/config_utils.go` file, `createProvider` function.
    -   [ ] add an icon on the user management dashboard.
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.
-   [ ] If access token structure has changed
    -   Modified test in `session/accessTokenVersions_test.go` to account for any new claims that are optional or omitted by the core

2024-05-01 13:47 UTC, rishabhpoddar requested changes

2024-05-01 13:47 UTC, rishabhpoddar commented on CHANGELOG.md
> +## [0.18.1] - 2024-05-01
this should be on top of the other duplicate cookie pr (as you had said)

2024-05-01 13:47 UTC, rishabhpoddar commented on recipe/session/session_utils_test.go
> + * Copyright (c) 2024, VRAI Labs and/or its affiliates. All rights reserved.
name of this file should be sessionUtils_tests.go (see how other test files are named)

2024-05-01 13:47 UTC, rishabhpoddar commented on recipe/session/session_utils_test.go
> +func TestNormaliseSessionScope(t *testing.T) {
add extra test cases from node pr

2024-05-02 17:13 UTC, closed without merging

2024-05-02 17:13 UTC, anku255 commented
Closing this. All the changes in this PR are moved to https://github.com/supertokens/supertokens-golang/pull/409