test: Added more unit tests for thirdpartyemailpassword recipe, JWT recipe and OpenId recipe
supertokens/supertokens-golang pull request #76
Opened 2022-03-12 06:57 UTC by rtpa25

## Summary of change

-  Added more tests to the thirdpartyemailpassword recipe
-  Added tests to JWT recipe 
-  Added tests to openID recipe 

## Related issues

-   https://github.com/supertokens/supertokens-golang/issues/24

## Test Plan

none

## Documentation changes

none

## Checklist for important updates

-   [x] Changelog has been updated
-   [ ] `coreDriverInterfaceSupported.json` file has been updated (if needed)
    -   Along with the associated array in `supertokens/constants.go`
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `supertokens/constants.go > version variable`
-   [x] Had installed and ran the pre-commit hook
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR

none

2022-03-14 06:35 UTC, rishabhpoddar requested changes

2022-03-14 06:35 UTC, rishabhpoddar commented on recipe/jwt/ovveride_test.go
> +/* Copyright (c) 2021, VRAI Labs and/or its affiliates. All rights reserved.
Typo in file name

2022-05-04 09:05 UTC, rtpa25 commented on recipe/jwt/ovveride_test.go
> +/* Copyright (c) 2021, VRAI Labs and/or its affiliates. All rights reserved.
Done

2022-05-04 09:15 UTC, rishabhpoddar requested changes

2022-05-04 09:15 UTC, rishabhpoddar commented on CHANGELOG.md
> +-   Adds test to opendID recipe
Need to move this up to unreleased section

2022-05-04 09:29 UTC, rishabhpoddar approved these changes

2022-05-04 10:21 UTC, merged